In [2]:
import pandas as pd
import numpy as np

In [3]:
pd.set_option('display.max_columns', None)

In [20]:
public_db = "./data/CBC data_for_meandeley_csv.csv"

In [280]:
df = pd.read_csv("./data/data-from-app.csv")
df_raw = df
df = df_raw.copy()

In [281]:
df.head()

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets,illnesses
0,12,female,48,69,160,B+,0,1,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0,0.0,0,0,0.0,0.0,0,0,0,0.0,0,0,...
1,13,female,45,70,170,A+,0,0,0,1,1,1.0,1.0,NaN,0,0,100.0,0.0,0,0.0,0,0,0.0,0.0,0,0,0,0.0,0,0,...
2,14,male,47,90,185,A+,0,0,0,0,0,2.0,2.0,łuszczyca,1,0,0.0,0.0,0,0.0,0,0,0.0,0.0,0,6,0,0.0,0,0,...
3,15,NaN,0,0,0,NaN,0,0,0,0,0,2.0,2.0,wrzód żołądka,1,0,0.0,0.0,0,0.0,0,0,0.0,6.0,0,0,0,0.0,0,0,...
4,16,female,7,24,132,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0,0.0,0,0,0.0,0.0,0,0,0,0.0,0,0,...

In [282]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 31 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            54 non-null     int64
 1   sex                49 non-null     object
 2   age                54 non-null     int64
 3   weight             54 non-null     int64
 4   height             54 non-null     int64
 5   blood_group        39 non-null     object
 6   smoker             54 non-null     int64
 7   vegan              54 non-null     int64
 8   supplements        54 non-null     int64
 9   regularity         54 non-null     int64
 10  pregnancy          54 non-null     int64
 11  frequency          52 non-null     float64
 12  covid              52 non-null     float64
 13  illnesses_input    18 non-null     object
 14  chronic_illness    54 non-null     int64
 15  all_parameters_ok  54 non-null     int64
 16  hb                 54 non-null     float64
 17  hct                54 non-null     float64
 18  mch                54 non-null     int64
 19  mchc               54 non-null     float64
 20  mcv                54 non-null     int64
 21  rcc                54 non-null     int64
 22  rdw                54 non-null     float64
 23  wbc                54 non-null     float64
 24  basophil           54 non-null     int64
 25  eosinophil         54 non-null     int64
 26  lymphocyte         54 non-null     int64
 27  monocyte           54 non-null     float64
 28  neutrophil         54 non-null     int64
 29  platelets          54 non-null     int64
 30  illnesses          54 non-null     object
dtypes: float64(8), int64(19), object(4)
memory usage: 13.2+ KB

In [283]:
for col in ['sex', 'blood_group', 'illnesses_input']:
    df[col] = df[col].astype('category')

# df['frequency'] = df['frequency'].astype('int')
# df['covid'] = df['covid'].astype('int')
df['mch'] = df['mch'].astype('float')
df['mcv'] = df['mcv'].astype('float')
df['rcc'] = df['rcc'].astype('float')
df['basophil'] = df['basophil'].astype('float')
df['eosinophil'] = df['eosinophil'].astype('float')
df['lymphocyte'] = df['lymphocyte'].astype('float')
df['neutrophil'] = df['neutrophil'].astype('float')
df['platelets'] = df['platelets'].astype('float')

In [284]:
df.drop('illnesses', axis=1, inplace=True)

In [285]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 54 entries, 0 to 53
Data columns (total 30 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   user_id            54 non-null     int64
 1   sex                49 non-null     category
 2   age                54 non-null     int64
 3   weight             54 non-null     int64
 4   height             54 non-null     int64
 5   blood_group        39 non-null     category
 6   smoker             54 non-null     int64
 7   vegan              54 non-null     int64
 8   supplements        54 non-null     int64
 9   regularity         54 non-null     int64
 10  pregnancy          54 non-null     int64
 11  frequency          52 non-null     float64
 12  covid              52 non-null     float64
 13  illnesses_input    18 non-null     category
 14  chronic_illness    54 non-null     int64
 15  all_parameters_ok  54 non-null     int64
 16  hb                 54 non-null     float64
 17  hct                54 non-null     float64
 18  mch                54 non-null     float64
 19  mchc               54 non-null     float64
 20  mcv                54 non-null     float64
 21  rcc                54 non-null     float64
 22  rdw                54 non-null     float64
 23  wbc                54 non-null     float64
 24  basophil           54 non-null     float64
 25  eosinophil         54 non-null     float64
 26  lymphocyte         54 non-null     float64
 27  monocyte           54 non-null     float64
 28  neutrophil         54 non-null     float64
 29  platelets          54 non-null     float64
dtypes: category(3), float64(16), int64(11)
memory usage: 12.8 KB

In [286]:
df.describe(include=['category']).T

                count unique           top freq
sex                49      2        female   27
blood_group        39      7            A+   15
illnesses_input    18     16  nadciśnienie    2

In [287]:
# df['user_id'] = df['user_id'].apply(lambda x: x - 12)

In [288]:
df.head()

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets
0,12,female,48,69,160,B+,0,1,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13,female,45,70,170,A+,0,0,0,1,1,1.0,1.0,NaN,0,0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14,male,47,90,185,A+,0,0,0,0,0,2.0,2.0,łuszczyca,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
3,15,NaN,0,0,0,NaN,0,0,0,0,0,2.0,2.0,wrzód żołądka,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16,female,7,24,132,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [289]:
df.loc[3, 'sex'] = 'male'
df.loc[3, 'age'] = 24
df.loc[3, 'weight'] = 83
df.loc[3, 'height'] = 180
df.loc[3, 'blood_group'] = 'A+'

In [290]:
df.head()

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets
0,12,female,48,69,160,B+,0,1,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13,female,45,70,170,A+,0,0,0,1,1,1.0,1.0,NaN,0,0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14,male,47,90,185,A+,0,0,0,0,0,2.0,2.0,łuszczyca,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
3,15,male,24,83,180,A+,0,0,0,0,0,2.0,2.0,wrzód żołądka,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16,female,7,24,132,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [291]:
df.isnull().sum()

user_id               0
sex                   4
age                   0
weight                0
height                0
blood_group          14
smoker                0
vegan                 0
supplements           0
regularity            0
pregnancy             0
frequency             2
covid                 2
illnesses_input      36
chronic_illness       0
all_parameters_ok     0
hb                    0
hct                   0
mch                   0
mchc                  0
mcv                   0
rcc                   0
rdw                   0
wbc                   0
basophil              0
eosinophil            0
lymphocyte            0
monocyte              0
neutrophil            0
platelets             0
dtype: int64

In [292]:
df[df['age'] == 0]

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets
12,24,NaN,0,0,0,NaN,0,0,0,0,0,NaN,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
28,41,NaN,0,0,0,NaN,1,0,0,0,0,3.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
36,49,NaN,0,0,0,NaN,0,0,0,0,0,NaN,NaN,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [293]:
df = df.drop(df[df['age'] == 0].index)

In [294]:
df['height'].min()

0

In [295]:
from sklearn.impute import SimpleImputer

In [296]:
imputer = SimpleImputer(missing_values=0, strategy='constant', fill_value=int(df['height'].mean()))
imputer.fit(df[['height']])

SimpleImputer(fill_value=165, missing_values=0, strategy='constant')

In [297]:
df['height'] = imputer.transform(df[['height']])
df

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets
0,12,female,48,69,160,B+,0,1,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13,female,45,70,170,A+,0,0,0,1,1,1.0,1.0,NaN,0,0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14,male,47,90,185,A+,0,0,0,0,0,2.0,2.0,łuszczyca,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
3,15,male,24,83,180,A+,0,0,0,0,0,2.0,2.0,wrzód żołądka,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16,female,7,24,132,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
5,17,male,3,17,101,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
6,18,male,10,32,145,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
7,19,female,70,85,165,B+,0,0,0,0,1,2.0,2.0,dystonia wegetatywnonaczyniowa,1,0,0.0,0.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
8,20,male,69,91,173,A+,0,0,0,0,0,2.0,2.0,nadciśnienie,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
9,21,female,71,84,171,A+,0,0,0,0,1,1.0,1.0,nadciśnienie,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,14.3,0.0,6.0,0.0,0.0,0.0,0.0
10,22,female,44,57,158,B-,0,0,0,0,0,2.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11,23,male,69,63,164,B+,0,0,0,0,0,3.0,3.0,astma,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
13,25,female,60,62,152,AB+,0,0,0,0,0,1.0,0.0,NaN,0,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
14,26,male,60,65,174,NaN,0,0,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
15,27,female,22,47,158,B-,0,0,0,0,0,1.0,2.0,zaburzenia lękowe,1,0,0.0,0.0,0.0,0.0,97.0,0.0,0.0,0.0,0.0,0.0,0.0,11.6,0.0,0.0
16,28,female,19,47,158,B-,0,0,0,0,0,1.0,0.0,zaburzenia lękowe,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
17,29,male,46,100,182,NaN,1,0,0,0,0,3.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18,30,NaN,47,80,174,A+,1,1,0,1,0,0.0,3.0,Hashimoto,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
19,31,female,31,60,168,B+,0,0,0,0,0,2.0,1.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
20,32,male,66,70,165,A+,1,0,0,0,0,0.0,0.0,"Rak prostaty, POCHP",1,0,0.0,39.8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21,33,male,59,107,165,A-,0,0,0,0,0,3.0,NaN,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
22,34,female,42,62,170,A+,0,0,0,0,0,2.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
23,36,female,22,58,165,0+,0,0,0,0,0,0.0,2.0,"Choroby jelit, depresja, stany lękowe, choroby...",1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
24,37,male,20,65,183,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25,38,male,22,88,188,NaN,0,0,0,1,0,0.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
26,39,female,21,58,180,B-,0,0,0,0,0,2.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27,40,male,21,82,182,B-,1,0,0,0,0,2.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
29,42,female,22,52,168,A+,1,0,0,1,0,0.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30,43,male,23,69,180,NaN,0,0,0,0,0,1.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
31,44,male,22,100,177,B+,0,0,0,1,0,0.0,3.0,tachykardia,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
32,45,male,22,75,177,B-,0,0,0,1,0,0.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
33,46,female,22,50,160,0+,1,0,0,1,0,0.0,1.0,ChAD,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
34,47,female,22,65,178,NaN,0,0,0,1,0,1.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
35,48,female,64,56,156,B+,0,0,0,0,0,3.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
37,50,female,46,79,164,NaN,0,0,0,0,1,2.0,0.0,"Cukrzycę, nadciśnienie",1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
38,51,male,21,70,178,NaN,1,0,0,0,0,1.0,0.0,Astma oskrzelowa,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
39,52,female,41,65,167,A+,0,0,0,0,1,2.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
40,53,female,21,63,180,A+,0,0,0,1,0,0.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
41,54,female,43,80,176,0-,0,0,0,0,0,1.0,2.0,NaN,0,0,10.9,0.0,0.0,30.7,0.0,0.0,17.1,0.0,0.0,0.0,0.0,0.0,0.0,0.0
42,55,female,24,80,180,NaN,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
43,56,male,26,65,186,NaN,0,0,0,0,0,2.0,2.0,"Niedoczynności tarczycy, astma",1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
44,57,male,49,67,176,AB+,1,0,0,0,0,3.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
45,58,female,46,76,172,NaN,1,1,0,0,0,2.0,3.0,Cukrzyca,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
46,59,female,21,53,164,0-,0,0,0,0,0,1.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
47,60,male,68,85,180,AB+,0,0,0,0,0,1.0,1.0,Kardiomiopatia,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
48,61,female,64,65,158,A+,1,0,0,0,1,1.0,1.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
49,62,male,72,80,168,0+,1,0,0,1,0,0.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
50,63,female,45,55,160,AB+,0,0,0,0,0,3.0,3.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
51,64,male,19,73,186,0-,0,0,0,0,0,2.0,0.0,NaN,0,0,0.0,0.0,35.0,0.0,98.0,0.0,0.0,0.0,0.0,0.0,0.0,12.2,0.0,0.0
52,65,female,62,75,173,0+,1,0,0,0,0,1.0,3.0,NaN,1,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
53,66,male,23,81,193,NaN,0,0,0,0,0,3.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [298]:
df['height'].min()

101

### Algorytm Apriori

In [17]:
from mlxtend.frequent_patterns import apriori, association_rules

In [299]:
df_apriori = df.copy()
df_apriori.head()

,user_id,sex,age,weight,height,blood_group,smoker,vegan,supplements,regularity,pregnancy,frequency,covid,illnesses_input,chronic_illness,all_parameters_ok,hb,hct,mch,mchc,mcv,rcc,rdw,wbc,basophil,eosinophil,lymphocyte,monocyte,neutrophil,platelets
0,12,female,48,69,160,B+,0,1,0,1,0,1.0,0.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,13,female,45,70,170,A+,0,0,0,1,1,1.0,1.0,NaN,0,0,100.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,14,male,47,90,185,A+,0,0,0,0,0,2.0,2.0,łuszczyca,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0
3,15,male,24,83,180,A+,0,0,0,0,0,2.0,2.0,wrzód żołądka,1,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0
4,16,female,7,24,132,A+,0,0,0,0,0,2.0,2.0,NaN,0,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [300]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['sex'])

In [301]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['blood_group'])

In [302]:
df_apriori.drop(['user_id', 'illnesses_input', 'hb', 'hct', 'mch', 'mchc', 'mcv', 'rcc', 'rdw', 'wbc', 'basophil', 'eosinophil', 'lymphocyte', 'monocyte', 'neutrophil', 'platelets'], axis=1, inplace=True)

In [303]:
df_apriori.loc[df_apriori['frequency'] == 1.0, 'frequency'] = 'once_a_year'
df_apriori.loc[df_apriori['frequency'] == 2.0, 'frequency'] = 'less_than_once_a_year'
df_apriori.loc[df_apriori['frequency'] == 3.0, 'frequency'] = 'hard_to_say'
df_apriori.loc[df_apriori['frequency'] == 0.0, 'frequency'] = 'more_than_once_a_year'
df_apriori['frequency'] = df_apriori['frequency'].fillna('hard_to_say')

In [304]:
df_apriori.loc[df_apriori['covid'] == 1.0, 'covid'] = 'two_weeks_from_covid'
df_apriori.loc[df_apriori['covid'] == 2.0, 'covid'] = 'more_than_two_weeks'
df_apriori.loc[df_apriori['covid'] == 3.0, 'covid'] = 'dont_know'
df_apriori.loc[df_apriori['covid'] == 0.0, 'covid'] = 'no_covid'
df_apriori['covid'] = df_apriori['covid'].fillna('dont_know')

In [305]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['frequency'])
df_apriori = pd.get_dummies(data=df_apriori, columns=['covid'])

In [306]:
df_test = df_apriori.copy()
df_test['height_cat'] = pd.cut(x=df_test.height, bins=(100, 170, 180, 195), labels=['short', 'medium', 'high'])
df_test

,age,weight,height,smoker,vegan,supplements,regularity,pregnancy,chronic_illness,all_parameters_ok,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid,height_cat
0,48,69,160,0,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,short
1,45,70,170,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,short
2,47,90,185,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,high
3,24,83,180,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,medium
4,7,24,132,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,short
5,3,17,101,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,short
6,10,32,145,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,short
7,70,85,165,0,0,0,0,1,1,0,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,short
8,69,91,173,0,0,0,0,0,1,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,medium
9,71,84,171,0,0,0,0,1,1,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,medium
10,44,57,158,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,short
11,69,63,164,0,0,0,0,0,1,1,0,1,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,short
13,60,62,152,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,1,0,0,1,0,short
14,60,65,174,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,medium
15,22,47,158,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,short
16,19,47,158,0,0,0,0,0,1,1,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,short
17,46,100,182,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,high
18,47,80,174,1,1,0,1,0,1,1,0,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,medium
19,31,60,168,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,short
20,66,70,165,1,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,short
21,59,107,165,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,short
22,42,62,170,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,short
23,22,58,165,0,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,1,0,0,short
24,20,65,183,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,high
25,22,88,188,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,high
26,21,58,180,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,1,0,0,1,0,0,0,medium
27,21,82,182,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,high
29,22,52,168,1,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,1,0,0,short
30,23,69,180,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,medium
31,22,100,177,0,0,0,1,0,1,1,0,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,medium
32,22,75,177,0,0,0,1,0,0,1,0,1,0,0,0,0,0,0,1,0,0,1,0,1,0,0,0,medium
33,22,50,160,1,0,0,1,0,1,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,short
34,22,65,178,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,medium
35,64,56,156,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,1,0,short
37,46,79,164,0,0,0,0,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,short
38,21,70,178,1,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,medium
39,41,65,167,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,1,0,short
40,21,63,180,0,0,0,1,0,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,1,0,medium
41,43,80,176,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,medium
42,24,80,180,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,medium
43,26,65,186,0,0,0,0,0,1,1,0,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,high
44,49,67,176,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,medium
45,46,76,172,1,1,0,0,0,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,medium
46,21,53,164,0,0,0,0,0,0,1,1,0,0,1,0,0,0,0,0,0,0,0,1,1,0,0,0,short
47,68,85,180,0,0,0,0,0,1,1,0,1,0,0,0,0,1,0,0,0,0,0,1,0,0,0,1,medium
48,64,65,158,1,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,short
49,72,80,168,1,0,0,1,0,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,1,0,short
50,45,55,160,0,0,0,0,0,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,short
51,19,73,186,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,high
52,62,75,173,1,0,0,0,0,1,1,1,0,1,0,0,0,0,0,0,0,0,0,1,1,0,0,0,medium
53,23,81,193,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,high

In [307]:
df_apriori['age'] = pd.cut(x=df_apriori.age, bins=3, labels=['young', 'mid', 'older'])
df_apriori.head()

,age,weight,height,smoker,vegan,supplements,regularity,pregnancy,chronic_illness,all_parameters_ok,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid
0,mid,69,160,0,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
1,mid,70,170,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,mid,90,185,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
3,young,83,180,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
4,young,24,132,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0

In [308]:
df_apriori['weight'] = pd.cut(x=df_apriori.weight, bins=3)
df_apriori.head()

,age,weight,height,smoker,vegan,supplements,regularity,pregnancy,chronic_illness,all_parameters_ok,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid
0,mid,"(47.0, 77.0]",160,0,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
1,mid,"(47.0, 77.0]",170,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,mid,"(77.0, 107.0]",185,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
3,young,"(77.0, 107.0]",180,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
4,young,"(16.91, 47.0]",132,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0

In [271]:
df_apriori['height'] = pd.cut(x=df_apriori.height, bins=(100, 170, 180, 195), labels=['short', 'medium', 'high'])
df_apriori.head()

,age,weight,height,smoker,vegan,supplements,regularity,pregnancy,chronic_illness,all_parameters_ok,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid
0,mid,"(47.0, 77.0]",short,0,1,0,1,0,0,1,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0
1,mid,"(47.0, 77.0]",short,0,0,0,1,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1
2,mid,"(77.0, 107.0]",high,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
3,young,"(77.0, 107.0]",medium,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0
4,young,"(16.91, 47.0]",short,0,0,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0

In [309]:
df_apriori.isnull().sum()

age                                0
weight                             0
height                             0
smoker                             0
vegan                              0
supplements                        0
regularity                         0
pregnancy                          0
chronic_illness                    0
all_parameters_ok                  0
sex_female                         0
sex_male                           0
blood_group_0+                     0
blood_group_0-                     0
blood_group_A+                     0
blood_group_A-                     0
blood_group_AB+                    0
blood_group_B+                     0
blood_group_B-                     0
frequency_hard_to_say              0
frequency_less_than_once_a_year    0
frequency_more_than_once_a_year    0
frequency_once_a_year              0
covid_dont_know                    0
covid_more_than_two_weeks          0
covid_no_covid                     0
covid_two_weeks_from_covid         0
dtype: int64

In [310]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['age'])

In [311]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['weight'])

In [312]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['height'])

In [313]:
df_apriori['all_parameters_ok'] = df_apriori['all_parameters_ok'].apply(lambda x: 'yes' if x == 1 else 'no')

In [315]:
df_apriori['chronic_illness'] = df_apriori['chronic_illness'].apply(lambda x: 'yes' if x == 1 else 'no')

In [317]:
df_apriori.head(10)

,smoker,vegan,supplements,regularity,pregnancy,chronic_illness,all_parameters_ok,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid,age_young,age_mid,age_older,"weight_(16.91, 47.0]","weight_(47.0, 77.0]","weight_(77.0, 107.0]",height_101,height_132,height_145,height_152,height_156,height_158,height_160,height_164,height_165,height_167,height_168,height_170,height_171,height_172,height_173,height_174,height_176,height_177,height_178,height_180,height_182,height_183,height_185,height_186,height_188,height_193
0,0,1,0,1,0,no,yes,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,1,1,no,no,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,0,0,0,0,0,yes,no,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0
3,0,0,0,0,0,yes,no,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0
4,0,0,0,0,0,no,yes,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,0,0,0,0,0,no,yes,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,0,0,0,0,0,no,yes,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,0,0,0,0,1,yes,no,1,0,0,0,0,0,0,1,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,0,0,0,0,0,yes,yes,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0
9,0,0,0,0,1,yes,no,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0

In [318]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['all_parameters_ok'])

In [319]:
df_apriori = pd.get_dummies(data=df_apriori, columns=['chronic_illness'])

In [320]:
df_apriori.head()

,smoker,vegan,supplements,regularity,pregnancy,sex_female,sex_male,blood_group_0+,blood_group_0-,blood_group_A+,blood_group_A-,blood_group_AB+,blood_group_B+,blood_group_B-,frequency_hard_to_say,frequency_less_than_once_a_year,frequency_more_than_once_a_year,frequency_once_a_year,covid_dont_know,covid_more_than_two_weeks,covid_no_covid,covid_two_weeks_from_covid,age_young,age_mid,age_older,"weight_(16.91, 47.0]","weight_(47.0, 77.0]","weight_(77.0, 107.0]",height_101,height_132,height_145,height_152,height_156,height_158,height_160,height_164,height_165,height_167,height_168,height_170,height_171,height_172,height_173,height_174,height_176,height_177,height_178,height_180,height_182,height_183,height_185,height_186,height_188,height_193,all_parameters_ok_no,all_parameters_ok_yes,chronic_illness_no,chronic_illness_yes
0,0,1,0,1,0,1,0,0,0,0,0,0,1,0,0,0,0,1,0,0,1,0,0,1,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0
1,0,0,0,1,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,1,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0
2,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,1
3,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,1
4,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,1,0

In [321]:
df_apriori.drop(['frequency_hard_to_say', 'covid_dont_know'], axis=1, inplace=True)

In [334]:
supports = apriori(df_apriori, min_support=0.3, use_colnames=True)

/home/dimatkchnk/.local/lib/python3.11/site-packages/mlxtend/frequent_patterns/fpcommon.py:110: DeprecationWarning: DataFrames with non-bool types result in worse computationalperformance and their support might be discontinued in the future.Please use a DataFrame with bool type
  warnings.warn(

In [336]:
rules = association_rules(supports, metric='confidence', min_threshold=0.2)
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction,zhangs_metric
0,(sex_female),"(weight_(47.0, 77.0])",0.529412,0.568627,0.372549,0.703704,1.237548,0.071511,1.455882,0.407895
1,"(weight_(47.0, 77.0])",(sex_female),0.568627,0.529412,0.372549,0.655172,1.237548,0.071511,1.364706,0.444976
2,(all_parameters_ok_yes),(sex_female),0.803922,0.529412,0.411765,0.512195,0.967480,-0.013841,0.964706,-0.146341
3,(sex_female),(all_parameters_ok_yes),0.529412,0.803922,0.411765,0.777778,0.967480,-0.013841,0.882353,-0.066667
4,(chronic_illness_no),(sex_female),0.627451,0.529412,0.352941,0.562500,1.062500,0.020761,1.075630,0.157895
5,(sex_female),(chronic_illness_no),0.529412,0.627451,0.352941,0.666667,1.062500,0.020761,1.117647,0.125000
6,(all_parameters_ok_yes),(sex_male),0.803922,0.450980,0.372549,0.463415,1.027572,0.009996,1.023173,0.136842
7,(sex_male),(all_parameters_ok_yes),0.450980,0.803922,0.372549,0.826087,1.027572,0.009996,1.127451,0.048872
8,(all_parameters_ok_yes),(age_young),0.803922,0.470588,0.411765,0.512195,1.088415,0.033449,1.085294,0.414286
9,(age_young),(all_parameters_ok_yes),0.470588,0.803922,0.411765,0.875000,1.088415,0.033449,1.568627,0.153439
10,(age_young),(chronic_illness_no),0.470588,0.627451,0.313725,0.666667,1.062500,0.018454,1.117647,0.111111
11,(chronic_illness_no),(age_young),0.627451,0.470588,0.313725,0.500000,1.062500,0.018454,1.058824,0.157895
12,(all_parameters_ok_yes),"(weight_(47.0, 77.0])",0.803922,0.568627,0.490196,0.609756,1.072330,0.033064,1.105392,0.344000
13,"(weight_(47.0, 77.0])",(all_parameters_ok_yes),0.568627,0.803922,0.490196,0.862069,1.072330,0.033064,1.421569,0.156364
14,(chronic_illness_no),"(weight_(47.0, 77.0])",0.627451,0.568627,0.411765,0.656250,1.154095,0.054979,1.254902,0.358396
15,"(weight_(47.0, 77.0])",(chronic_illness_no),0.568627,0.627451,0.411765,0.724138,1.154095,0.054979,1.350490,0.309524
16,(all_parameters_ok_yes),(chronic_illness_no),0.803922,0.627451,0.549020,0.682927,1.088415,0.044598,1.174962,0.414286
17,(chronic_illness_no),(all_parameters_ok_yes),0.627451,0.803922,0.549020,0.875000,1.088415,0.044598,1.568627,0.218045
18,"(all_parameters_ok_yes, sex_female)","(weight_(47.0, 77.0])",0.411765,0.568627,0.333333,0.809524,1.423645,0.099193,2.264706,0.505882
19,"(all_parameters_ok_yes, weight_(47.0, 77.0])",(sex_female),0.490196,0.529412,0.333333,0.680000,1.284444,0.073818,1.470588,0.434389
20,"(sex_female, weight_(47.0, 77.0])",(all_parameters_ok_yes),0.372549,0.803922,0.333333,0.894737,1.112965,0.033833,1.862745,0.161765
21,(all_parameters_ok_yes),"(sex_female, weight_(47.0, 77.0])",0.803922,0.372549,0.333333,0.414634,1.112965,0.033833,1.071895,0.517647
22,(sex_female),"(all_parameters_ok_yes, weight_(47.0, 77.0])",0.529412,0.490196,0.333333,0.629630,1.284444,0.073818,1.376471,0.470588
23,"(weight_(47.0, 77.0])","(all_parameters_ok_yes, sex_female)",0.568627,0.411765,0.333333,0.586207,1.423645,0.099193,1.421569,0.689840
24,"(all_parameters_ok_yes, chronic_illness_no)","(weight_(47.0, 77.0])",0.549020,0.568627,0.352941,0.642857,1.130542,0.040754,1.207843,0.256039
25,"(all_parameters_ok_yes, weight_(47.0, 77.0])",(chronic_illness_no),0.490196,0.627451,0.352941,0.720000,1.147500,0.045367,1.330532,0.252137
26,"(chronic_illness_no, weight_(47.0, 77.0])",(all_parameters_ok_yes),0.411765,0.803922,0.352941,0.857143,1.066202,0.021915,1.372549,0.105556
27,(all_parameters_ok_yes),"(chronic_illness_no, weight_(47.0, 77.0])",0.803922,0.411765,0.352941,0.439024,1.066202,0.021915,1.048593,0.316667
28,(chronic_illness_no),"(all_parameters_ok_yes, weight_(47.0, 77.0])",0.627451,0.490196,0.352941,0.562500,1.147500,0.045367,1.165266,0.345029
29,"(weight_(47.0, 77.0])","(all_parameters_ok_yes, chronic_illness_no)",0.568627,0.549020,0.352941,0.620690,1.130542,0.040754,1.188948,0.267677

In [19]:
# df.to_csv('./data/data-from-app-processed.csv', index=False)

## Public database

In [37]:
dfp = pd.read_csv(public_db)

In [38]:
dfp.shape

(374, 12)

In [39]:
dfp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 374 entries, 0 to 373
Data columns (total 12 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   S. No.     364 non-null    float64
 1   Age        364 non-null    float64
 2   Sex        364 non-null    float64
 3     RBC      365 non-null    object
 4   PCV        365 non-null    object
 5   MCV        365 non-null    object
 6   MCH        365 non-null    object
 7    MCHC      364 non-null    float64
 8    RDW       365 non-null    object
 9   TLC        365 non-null    object
 10   PLT /mm3  365 non-null    object
 11   HGB       365 non-null    object
dtypes: float64(4), object(8)
memory usage: 35.2+ KB

In [41]:
dfp.head()

,S. No.,Age,Sex,RBC,PCV,MCV,MCH,MCHC,RDW,TLC,PLT /mm3,HGB
0,NaN,NaN,NaN,Red Blood Cell count,Packed Cell Volume,Mean Cell Volume,Mean Cell Hemoglobin,NaN,Red Cell Distribution width,"White Blood Cell (WBC count),",Platelet,Hemoglobin
1,1.0,28.0,0.0,5.66,34,60.1,17,28.2,20,11.1,128.3,9.6
2,2.0,41.0,0.0,4.78,44.5,93.1,28.9,31.0,13,7.02,419,13.8
3,3.0,40.0,1.0,4.65,41.6,89.5,28.8,32.2,13,8.09,325,13.4
4,4.0,76.0,0.0,4.24,36.7,86.6,26.7,30.8,14.9,13.41,264,11.3